export const FETCH_TODOS_PENDING = 'FETCH_TODOS_PENDING';
export const FETCH_TODOS_FULFILLED = 'FETCH_TODOS_FULFILLED';
export const FETCH_TODOS_REJECTED = 'FETCH_TODOS_REJECTED';

export const CREATE_TODO_PENDING = 'CREATE_TODO_PENDING';
export const CREATE_TODO_FULFILLED = 'CREATE_TODO_FULFILLED';
export const CREATE_TODO_REJECTED = 'CREATE_TODO_REJECTED';

export const UPDATE_TODO_PENDING = 'UPDATE_TODO_PENDING';
export const UPDATE_TODO_FULFILLED = 'UPDATE_TODO_FULFILLED';
export const UPDATE_TODO_REJECTED = 'UPDATE_TODO_REJECTED';

export const DELETE_TODO_PENDING = 'DELETE_TODO_PENDING';
export const DELETE_TODO_FULFILLED = 'DELETE_TODO_FULFILLED';
export const DELETE_TODO_REJECTED = 'DELETE_TODO_REJECTED';